#!/bin/bash

# extra preparation when compiling on the OSG submit host
if [[ $(hostname) == 'xd-login.opensciencegrid.org' ]]; then
  # load lmod
  source /cvmfs/oasis.opensciencegrid.org/osg/modules/lmod/current/init/bash

  # load necessary modules:
  #  - recent version of gcc, for c++11 among other things
  #  - recent version of cmake
  #  - boost for c++ codes
  #  - hdf5 for trento
  #  - python and packages for generating the vishnew EOS table
  module purge
  module load gcc cmake boost hdf5 python/3.4 all-pkgs

  # the modules set the standard environment variables CPATH and LIBRARY_PATH
  # set corresponding variables for cmake
  export CMAKE_INCLUDE_PATH=$CPATH
  export CMAKE_LIBRARY_PATH=$LIBRARY_PATH

  # set c++ and fortran compiler flags
  export CXXFLAGS="-march=x86-64 -mtune=intel"
  export FFLAGS="$CXXFLAGS"

  # explicitly set fortran compiler to override cmake default
  export FC='gfortran'

  # set linker flags to prefer the module versions of libraries to the system versions
  # the linker reads $LIBRARY_PATH but gives it lower priority than the standard paths
  # this uses -L flags to give $LIBRARY_PATH higher priority
  export LDFLAGS="-L${LIBRARY_PATH//:/ -L}"
fi

pkgname='hic-osg'

# create a temporary directory for installing files
installdir=$(mktemp --directory)
# and ensure it's cleaned on exit
trap "rm -r $installdir" EXIT

# build each model
for i in models/*/; do
  pushd $i

  # create build directory and run cmake if necessary
  if [[ -d build ]]; then
    cd build
  else
    mkdir build && cd build
    # disable install prefix by setting it to "/"
    # the actual install location will be set by DESTDIR later
    cmake \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX="/" \
      .. || exit 1
  fi

  # compile and install to the temporary directory
  make --jobs=$(nproc) DESTDIR=$installdir/$pkgname install || exit 1

  popd
done

# install the event runner script
cp -v models/run-events $installdir/$pkgname

# create tgz for distributing to each job
tar --verbose --create --gzip --file $pkgname.tar.gz \
  --directory $installdir $pkgname
