#!/bin/bash
#SBATCH --qos regular
#SBATCH --constraint haswell
#SBATCH --nodes 20
#SBATCH --ntasks-per-node 1
#SBATCH --time 01:00:00
#SBATCH --license cscratch1
#SBATCH --mail-type ALL
#SBATCH --mail-user <email>
#SBATCH --output  /global/cscratch1/sd/<user>/slurm/%x-%j
#SBATCH --error   /global/cscratch1/sd/<user>/slurm/%x-%j

export CONDA_PREFIX=/global/common/software/<project>/<prefix>
export PATH=$CONDA_PREFIX/bin:$PATH
export XDG_DATA_HOME=$CONDA_PREFIX/share

workdir=$CSCRATCH/taskfarmer/$SLURM_JOB_NAME-$NERSC_HOST-$SLURM_JOB_ID
mkdir -p $workdir
cd $workdir

find $CSCRATCH/checkpoints -type f | sed 's/^/run-events checkpoint /' > tasks

module load taskfarmer
runcommands.sh tasks
