#!/bin/bash
#SBATCH --qos regular
#SBATCH --constraint haswell
#SBATCH --nodes 100
#SBATCH --cpus-per-task 1
#SBATCH --time 10:00:00
#SBATCH --license cscratch1
#SBATCH --mail-type ALL
#SBATCH --mail-user <email>
#SBATCH --output  /global/cscratch1/sd/<user>/slurm/%x-%j
#SBATCH --error   /global/cscratch1/sd/<user>/slurm/%x-%j
#SBATCH --workdir /global/cscratch1/sd/<user>/inputfiles

export CONDA_PREFIX=/global/common/software/<project>/<prefix>
export PATH=$CONDA_PREFIX/bin:$PATH
export XDG_DATA_HOME=$CONDA_PREFIX/share

# broadcast executable to compute nodes (for large scale jobs)
exe=design-wrapper
sbcast /path/to/$exe /tmp/$exe  # change source path to actual location

# change path to match all design input files
srun /tmp/$exe relpath/to/inputfiles/*
