#!/bin/bash

# gather system data
uname -nr

# read arguments
inputfile=$1
desturl=$2

# load necessary modules
source /cvmfs/oasis.opensciencegrid.org/osg/modules/lmod/current/init/bash
module load python/3.5.2 all-pkgs gcc/6.2.0 boost/1.62.0-cxx11 hdf5/1.8.13-cxx11 || exit 1

# unpack package
pkgname='hic-osg'
tar xzf $pkgname.tar.gz

# set environment variables
prefix="$(pwd)/$pkgname"
export PATH="$prefix/bin:$PATH"
export XDG_DATA_HOME="$prefix/share"
export PYTHONPATH="$(echo $prefix/lib/python*/site-packages)"

# go!
run-events \
  --nevents 10 \
  --tmpdir . \
  @$inputfile \
  results || exit 1

# transfer results
# try to be fault-tolerant
globus() {
  globus-url-copy \
    -verbose -create-dest -restart -stall-timeout 30 $@ \
    results $desturl
}

for i in {1..5}; do
  globus && break
  sleep 5 && false
done || \
  globus -no-data-channel-authentication -no-third-party-transfers
