#!/bin/bash

# gather system data
uname -nr

# read arguments
inputfile=$1
desturl=$2

# load necessary modules
source /cvmfs/oasis.opensciencegrid.org/osg/modules/lmod/current/init/bash
module load python/3.5.2 all-pkgs gcc boost hdf5 || exit 1

# unpack package
pkgname='hic-osg'
tar xzf $pkgname.tar.gz

# set environment variables
export PATH="$(pwd)/$pkgname/bin:$PATH"
export XDG_DATA_HOME="$(pwd)/$pkgname/share"

# go!
run-events $inputfile || exit 1

# transfer results
# try to be fault-tolerant
globus() {
  globus-url-copy \
    -verbose -create-dest -restart -stall-timeout 30 $@ \
    results $desturl
}

for i in {1..5}; do
  globus && break
  sleep 5 && false
done || \
  globus -no-data-channel-authentication -no-third-party-transfers
