#!/bin/bash

# gather system data
uname -nr

# read arguments
inputfile=$1
desturl=$2

# load necessary modules
source /cvmfs/oasis.opensciencegrid.org/osg/modules/lmod/current/init/bash
module load python/3.4 all-pkgs gcc boost hdf5 || exit 1

# unpack package
pkgname='hic-osg'
tar xzf $pkgname.tar.gz
cd $pkgname

# run the events
./run-events ../$inputfile || exit 1

# transfer results
# try to be fault-tolerant
globus() {
  globus-url-copy \
    -verbose -create-dest -restart -stall-timeout 30 $@ \
    results.hdf $desturl
}
globus || globus -no-data-channel-authentication -no-third-party-transfers
